services:
  web:
    build: .
    platform: linux/amd64
    container_name: gpw-web
    ports:
      - 9000:80
      - 9002:9002 # vite
      - 35729:35729 # livereload
    depends_on:
      - memcached
      - mysql
    volumes:
      - .:/var/www:delegated
      - .docker/web/nginx.conf:/etc/nginx/sites-enabled/gazelle.conf
      - .docker/web/www.conf:/etc/php/8.4/fpm/pool.d/www.conf
    environment:
      # These should match what you set for your mysql container below
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  memcached:
    image: memcached:latest
    container_name: gpw-memcached
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: gpw-phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - mysql
    ports:
      - 9001:80
  mysql:
    image: mariadb:latest
    container_name: gpw-mysql
    ports:
      - 36000:3306
    volumes:
      - ./.docker/mysql/mysqld_sql_mode.cnf:/etc/mysql/conf.d/mysqld_sql_mode.cnf:ro
      - mysql-data:/var/lib/mysql
      - ./gazelle.sql:/docker-entrypoint-initdb.d/gazelle.sql:ro
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  manticoresearch:
    build: ./.docker/manticore
    platform: linux/amd64
    container_name: gpw-manticoresearch
    depends_on:
      - mysql
      - web
    volumes:
      - manticore-data:/var/lib/manticore
      - ./.docker/manticore/manticore.conf:/var/lib/manticore/conf/manticore.conf
    environment:
      # These should match what you set for your mysql container above
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  mysql-data:
  manticore-data:
